/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadersRouteImport } from './routes/readers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AiTarotRouteImport } from './routes/ai-tarot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderReaderIdRouteImport } from './routes/reader.$readerId'
import { Route as BookingReaderIdRouteImport } from './routes/booking.$readerId'

const ReadersRoute = ReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTarotRoute = AiTarotRouteImport.update({
  id: '/ai-tarot',
  path: '/ai-tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderReaderIdRoute = ReaderReaderIdRouteImport.update({
  id: '/reader/$readerId',
  path: '/reader/$readerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReaderIdRoute = BookingReaderIdRouteImport.update({
  id: '/booking/$readerId',
  path: '/booking/$readerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-tarot': typeof AiTarotRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/readers': typeof ReadersRoute
  '/booking/$readerId': typeof BookingReaderIdRoute
  '/reader/$readerId': typeof ReaderReaderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-tarot': typeof AiTarotRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/readers': typeof ReadersRoute
  '/booking/$readerId': typeof BookingReaderIdRoute
  '/reader/$readerId': typeof ReaderReaderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-tarot': typeof AiTarotRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/readers': typeof ReadersRoute
  '/booking/$readerId': typeof BookingReaderIdRoute
  '/reader/$readerId': typeof ReaderReaderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-tarot'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/readers'
    | '/booking/$readerId'
    | '/reader/$readerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-tarot'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/readers'
    | '/booking/$readerId'
    | '/reader/$readerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-tarot'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/readers'
    | '/booking/$readerId'
    | '/reader/$readerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiTarotRoute: typeof AiTarotRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ReadersRoute: typeof ReadersRoute
  BookingReaderIdRoute: typeof BookingReaderIdRoute
  ReaderReaderIdRoute: typeof ReaderReaderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readers': {
      id: '/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof ReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tarot': {
      id: '/ai-tarot'
      path: '/ai-tarot'
      fullPath: '/ai-tarot'
      preLoaderRoute: typeof AiTarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$readerId': {
      id: '/reader/$readerId'
      path: '/reader/$readerId'
      fullPath: '/reader/$readerId'
      preLoaderRoute: typeof ReaderReaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$readerId': {
      id: '/booking/$readerId'
      path: '/booking/$readerId'
      fullPath: '/booking/$readerId'
      preLoaderRoute: typeof BookingReaderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiTarotRoute: AiTarotRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ReadersRoute: ReadersRoute,
  BookingReaderIdRoute: BookingReaderIdRoute,
  ReaderReaderIdRoute: ReaderReaderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
